---
title: "Covariate clearing"
author: "Insang Song"
date: 02-12-2022
theme: "spacelab"
output:
  html_document:
    toc: true
    fig_caption: true
---

```{r}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```




```{r}
source('./base_functions.R')
options(repos = 'https://cran.seoul.go.kr')
if (!require(pacman)) { install.packages('pacman') } 

p_load(tidyverse, sf, stars, raster, starsExtra, readxl, here, tmap, stargazer, smerc, DClusterm, kableExtra, patchwork)

username = 'sigma'
basedir = sprintf('/mnt/c/Users/%s/', username)
rdatafiles = list.files(path = str_c(basedir, 'Documents/GP/'), pattern = '*.RData', full.names = TRUE)
geopath = str_c(basedir, "OneDrive/Data/Korea/")
#homedir <- "/home/felix/"
drive = str_c(basedir, "OneDrive/NCC_Project/CancerClustering/")
geopath = str_c(basedir, "OneDrive/Data/Korea/")
dbdir = drive  # here::here()

```


```{r data munging, include = FALSE}
# incidence
inc <- read.csv(paste(drive, "cancerInc_sgg.csv", sep = ""), fileEncoding = "EUC-KR")
mor_to <- read.csv(paste(drive, "cancerMor_sgg_total.csv", sep = ""), fileEncoding = "EUC-KR")
mor_me <- read.csv(paste(drive, "cancerMor_sgg_male.csv", sep = ""), fileEncoding = "EUC-KR")
mor_fe <- read.csv(paste(drive, "cancerMor_sgg_female.csv", sep = ""), fileEncoding = "EUC-KR")

conv_table = read.csv(paste(geopath, 'SGG_1995_2018_Conversion_Table_201108.csv', sep = ''), fileEncoding = 'EUC-KR')
# total population for the expected values
# sex code: 0(all), 1(male), 2(female)
pop <- read.csv(paste(drive, "Midyear_Population_1998_2019.csv", sep = ""), fileEncoding = "UTF-8") %>%
    mutate(
        sex0 = plyr::mapvalues(sex0, c(0, 1, 2), c("T", "M", "F")),
        sex_e = plyr::mapvalues(sex0, c("T", "M", "F"), c("Total", "Male", "Female")),
        population = as.numeric(population)
    )
pop_wide = pop %>%
    pivot_wider(names_from = c("sex0", "year"), values_from = population)

colnames(inc) <- c("sex0", "sex", "cancer_type0", "cancer_type", "sgg_cd", "sgg_nm", "year0", "year", "inc0", "type_inc", "unit", "n", "x")
colnames(mor_to) <- c("cause0", "cause", "sgg_cd", "sgg_nm", "sex0", "sex", "type0", "type", "unit", paste("Y", 1998:2019, sep = ""), "x")
colnames(mor_me) <- c("cause0", "cause", "sgg_cd", "sgg_nm", "sex0", "sex", "type0", "type", "unit", paste("Y", 1998:2019, sep = ""), "x")
colnames(mor_fe) <- c("cause0", "cause", "sgg_cd", "sgg_nm", "sex0", "sex", "type0", "type", "unit", paste("Y", 1998:2019, sep = ""), "x")


## Data preprocessing ####
sgg <- st_read(paste(geopath, "SGG_Merge_2000_2016.shp", sep = ""))
sgg2010 <- sgg %>%
    filter(BASE_YEAR == 2010)
conv_table_e = conv_table %>%
    filter(from_year >= 1999 & from_year <= 2013) %>%
    dplyr::select(fromcode, tocode)

pop_cl = pop %>%
    mutate(sgg_cd = plyr::mapvalues(sgg_cd, conv_table_e$fromcode, conv_table_e$tocode),
           year_agg = cut(year, breaks = c(1998,2003,2008,2013,2018,2019), labels = c('1999-2003', '2004-2008', '2009-2013', '2014-2018', '2019'), right = TRUE)) %>%
    group_by(year_agg, sgg_cd, sex0, sex_e) %>%
    summarize(population = sum(population, na.rm = TRUE)) %>%
    ungroup


inc_cl <- inc %>%
    mutate(
        n_n = as.numeric(n),
        n_n = ifelse(is.na(n_n), 0, n_n),
        cancer_type_e = plyr::mapvalues(cancer_type, unique(cancer_type), c("Stomach", "Colorectal", "Liver", "Lung", "Breast", "Cervical", "Prostate", "Thyroid")),
        sex_e = plyr::mapvalues(sex, unique(sex), c("Total", "Male", "Female")),
        type_inc_e = plyr::mapvalues(type_inc, unique(type_inc), c("N", "r_crude", "r_agest")),
        sgg_cd_c = plyr::mapvalues(sgg_cd, conv_table_e$fromcode, conv_table_e$tocode)
    ) %>%
    # not sum
    pivot_wider(id_cols = c(year, sgg_cd_c, cancer_type_e, sex_e), names_from = type_inc_e, values_from = n_n, values_fn = function(x) sum(x, na.rm = TRUE)) %>%
    # note that sex-specific cancers have incorrect crude rates
    left_join(pop_cl, by = c('year' = 'year_agg', 'sgg_cd_c' = 'sgg_cd', 'sex_e' = 'sex_e')) %>%
    group_by(year, sgg_cd_c, cancer_type_e, sex_e) %>%
    summarize(Ntotal = sum(N, na.rm = T),
              r_crude = sum(r_crude * (population / sum(population, na.rm = T)), na.rm = T)) %>%
    ungroup %>%
    pivot_longer(cols = 5:6, values_to = 'n_n', names_to = 'type_inc_e')

# summary table
inc_cl_summary <- inc_cl %>%
    group_by(cancer_type_e, year, sex_e, type_inc_e) %>%
    summarize(
        n_nmin = min(n_n),
        n_nmedian = median(n_n),
        n_nmean = mean(n_n),
        n_nmax = max(n_n)
    ) %>%
    ungroup() %>%
    pivot_longer(cols = 5:8) %>%
    pivot_wider(names_from = c("sex_e", "name"))

mor_cl = bind_rows(mor_to, mor_me) %>%
    bind_rows(mor_fe) %>%
    pivot_longer(cols = Y1998:Y2019) %>%
    mutate(year = as.integer(str_sub(name, 2, 5)),
           year_agg = cut(year, breaks = c(1998,2003,2008,2013,2018,2019), labels = c('1999-2003', '2004-2008', '2009-2013', '2014-2018', '2019'), right = TRUE),
           cancer_type_e = plyr::mapvalues(cause, unique(cause), c("Stomach", "Colorectal", "Liver", "Lung/Bronchus", "Breast", "Cervical/Uterine", "Prostate")),
           sex_e = plyr::mapvalues(sex, unique(sex), c('Total', 'Male', 'Female')),
           type_mor_e = plyr::mapvalues(type0, c('T1', 'T4', 'T7'), c('N', 'r_crude', 'r_agest')),
           sgg_cd_c = plyr::mapvalues(sgg_cd, conv_table_e$fromcode, conv_table_e$tocode)
        ) %>%
    # not sum
    pivot_wider(id_cols = c(year_agg, sgg_cd_c, cancer_type_e, sex_e), names_from = type_mor_e, values_from = value, values_fn = function(x) sum(x, na.rm = TRUE)) %>%
    left_join(pop_cl, by = c('year_agg' = 'year_agg', 'sgg_cd_c' = 'sgg_cd', 'sex_e' = 'sex_e')) %>%
    group_by(year_agg, sgg_cd_c, cancer_type_e, sex_e) %>%
    summarize(Ntotal = sum(N, na.rm = T),
              r_crude = 1e5 * sum(N, na.rm = T)/sum(population, na.rm = T)) %>%
    ungroup %>%
    filter(year_agg %in% c('1999-2003', '2004-2008', '2009-2013'))
```

```{r Aggregated data: pop mort inc, include = FALSE, eval = FALSE}
### Incidence-Mortality consolidation ####
## Mortality
mor_clw = mor_cl %>%
    filter(cancer_type_e %in% c('Stomach', 'Lung/Bronchus')) %>%
    mutate(sex_e = tolower(sex_e),
           cancer_type_e = ifelse(cancer_type_e == 'Lung/Bronchus', 'Lung', cancer_type_e)) %>%
    rename(n = Ntotal) %>%
    mutate(period = plyr::mapvalues(year_agg, unique(year_agg), seq_len(length(unique(year_agg))))) %>%
    dplyr::select(-year_agg, -r_crude) %>%
    filter(period %in% 1:3) %>%
    pivot_wider(names_from = c(cancer_type_e, sex_e, period),
                names_sep = "_",
                names_prefix = "n_d_",
                values_from = n)    

## Incidence
inc_clw = inc_cl %>%
    filter(cancer_type_e %in% c('Stomach', 'Lung') & type_inc_e == "Ntotal") %>%
    mutate(sex_e = tolower(sex_e),
           type_inc_e = 'n') %>%
    mutate(period = plyr::mapvalues(year, unique(year), seq_len(length(unique(year))))) %>%
    dplyr::select(-year, -type_inc_e) %>%
    pivot_wider(names_from = c(cancer_type_e, sex_e, period),
                names_sep = "_",
                names_prefix = 'n_i_',
                values_from = n_n)    

## Population (5-year aggregation)
pop_clw = pop_cl %>%
    mutate(sex_e = tolower(sex_e),
           period = plyr::mapvalues(year_agg, unique(year_agg), seq_len(length(unique(year_agg))))) %>%
    dplyr::select(-sex0, -year_agg) %>%
    filter(period %in% 1:3) %>%
    pivot_wider(names_from = c(sex_e, period),
                names_sep = "_",
                names_prefix = 'n_p_',
                values_from = population) %>%
    dplyr::select(-ends_with('_NA'))


## Joined mortality-incidence-population (5-year aggregated)
morinc_clw = mor_clw %>%
    full_join(inc_clw) %>%
    full_join(pop_clw, by = c('sgg_cd_c' = 'sgg_cd'))

```


```{r Summary plots}
inc_clgg_n = inc_cl %>%
    filter(cancer_type_e %in% c('Lung', 'Stomach') & type_inc_e == 'Ntotal') %>%
    ggplot(data = .,
           mapping = aes(x = year, y = n_n, group = interaction(year, cancer_type_e, sex_e))) +
        facet_grid(sex_e ~ cancer_type_e) +
        geom_boxplot() +
        theme_bw() +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
        #scale_y_continuous(limits = c(0, 225)) +
        labs(subtitle = 'Crude cancer incidence counts by five-year periods and types')

inc_clgg_r = inc_cl %>%
    filter(cancer_type_e %in% c('Lung', 'Stomach') & type_inc_e == 'r_crude') %>%
    ggplot(data = .,
           mapping = aes(x = year, y = n_n, group = interaction(year, cancer_type_e, sex_e))) +
        facet_grid(sex_e ~ cancer_type_e) +
        geom_boxplot() +
        theme_bw() +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
        #scale_y_continuous(limits = c(0, 225)) +
        labs(subtitle = 'Crude cancer incidence rates per 100,000 persons by five-year periods and types')


mor_clgg_n = mor_cl %>%
    filter(cancer_type_e %in% c('Lung/Bronchus', 'Stomach')) %>%
    #left_join(pop, by = c('sgg_cd' = 'sgg_cd', 'year' = 'year', 'sex_e' = 'sex_e')) %>%
    #group_by(sgg_cd, cause, cancer_type_e, sex_e, year_agg) %>%
    #summarize(rate_100k_5yr = 1e5 * (sum(value, na.rm = T)/sum(population, na.rm = T))) %>%
    #ungroup %>%
    ggplot(data = .,
           mapping = aes(x= year_agg, y = Ntotal, group = interaction(year_agg, cancer_type_e, sex_e))) +
        facet_grid(sex_e ~ cancer_type_e) +
        geom_boxplot() +
        theme_bw() +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
        #scale_y_continuous(limits = c(0, 225)) +
        labs(subtitle = 'Cancer mortality counts by years and types')


mor_clgg_r = mor_cl %>%
    filter(cancer_type_e %in% c('Lung/Bronchus', 'Stomach')) %>%
    #left_join(pop, by = c('sgg_cd' = 'sgg_cd', 'year' = 'year', 'sex_e' = 'sex_e')) %>%
    #group_by(sgg_cd, cause, cancer_type_e, sex_e, year_agg) %>%
    #summarize(rate_100k_5yr = 1e5 * (sum(value, na.rm = T)/sum(population, na.rm = T))) %>%
    #ungroup %>%
    ggplot(data = .,
           mapping = aes(x= year_agg, y = r_crude, group = interaction(year_agg, cancer_type_e, sex_e))) +
        facet_grid(sex_e ~ cancer_type_e) +
        geom_boxplot() +
        theme_bw() +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
        #scale_y_continuous(limits = c(0, 225)) +
        labs(subtitle = 'Crude cancer mortality rates per 100,000 persons by years and types')

(inc_clgg_n | mor_clgg_n)

(inc_clgg_r | mor_clgg_r)

```


```{r data cleaning, eval = FALSE, include = FALSE}
covar_origin_10 = get_basecovar(target_year = 2010)
covar_origin_10_fc = clean_consolidated(cleaned_df = covar_origin_10) %>%
    mutate_at(.vars = vars(-geom),
              .funs = list(~ifelse(is.na(.), median(., na.rm = TRUE), .))) %>%
    left_join(morinc_clw, by = c('sgg_cd_c'))

```

```{r Run main analysis, include = FALSE, eval = FALSE}
# Naming: smerc_[cancertype]_[period][incidence/mortality][sex][uncontrolled]
# Incidence (i)
smerc_lung_3it = run_smerc_cancertype(data = covar_origin_10_fc, yvar = 'n_i_Lung_total_3', sex_b = 'total', adjust = TRUE, ncores = 24)
smerc_stom_3it = run_smerc_cancertype(data = covar_origin_10_fc, yvar = 'n_i_Stomach_total_3', sex_b = 'total', adjust = TRUE, ncores = 24)
smerc_lung_3im = run_smerc_cancertype(data = covar_origin_10_fc, yvar = 'n_i_Lung_male_3', sex_b = 'male', adjust = TRUE, ncores = 24)
smerc_stom_3im = run_smerc_cancertype(data = covar_origin_10_fc, yvar = 'n_i_Stomach_male_3', sex_b = 'male', adjust = TRUE, ncores = 24)
smerc_lung_3if = run_smerc_cancertype(data = covar_origin_10_fc, yvar = 'n_i_Lung_female_3', sex_b = 'female', adjust = TRUE, ncores = 24)
smerc_stom_3if = run_smerc_cancertype(data = covar_origin_10_fc, yvar = 'n_i_Stomach_female_3', sex_b = 'female', adjust = TRUE, ncores = 24)


smerc_lung_3itu = run_smerc_cancertype(data = covar_origin_10_fc, pop = 'n_p_total_3', yvar = 'n_i_Lung_total_3', sex_b = 'total', adjust = FALSE, ncores = 24)
smerc_stom_3itu = run_smerc_cancertype(data = covar_origin_10_fc, pop = 'n_p_total_3', yvar = 'n_i_Stomach_total_3', sex_b = 'total', adjust = FALSE, ncores = 24)
smerc_lung_3imu = run_smerc_cancertype(data = covar_origin_10_fc, pop = 'n_p_male_3', yvar = 'n_i_Lung_male_3', sex_b = 'male', adjust = FALSE, ncores = 24)
smerc_stom_3imu = run_smerc_cancertype(data = covar_origin_10_fc, pop = 'n_p_male_3', yvar = 'n_i_Stomach_male_3', sex_b = 'male', adjust = FALSE, ncores = 24)
smerc_lung_3ifu = run_smerc_cancertype(data = covar_origin_10_fc, pop = 'n_p_female_3', yvar = 'n_i_Lung_female_3', sex_b = 'female', adjust = FALSE, ncores = 24)
smerc_stom_3ifu = run_smerc_cancertype(data = covar_origin_10_fc, pop = 'n_p_female_3', yvar = 'n_i_Stomach_female_3', sex_b = 'female', adjust = FALSE, ncores = 24)

# Mortality (d)
smerc_lung_3dt = run_smerc_cancertype(data = covar_origin_10_fc, yvar = 'n_d_Lung_total_3', sex_b = 'total', adjust = TRUE, ncores = 16)
smerc_stom_3dt = run_smerc_cancertype(data = covar_origin_10_fc, yvar = 'n_d_Stomach_total_3', sex_b = 'total', adjust = TRUE, ncores = 16)
smerc_lung_3dm = run_smerc_cancertype(data = covar_origin_10_fc, yvar = 'n_d_Lung_male_3', sex_b = 'male', adjust = TRUE, ncores = 16)
smerc_stom_3dm = run_smerc_cancertype(data = covar_origin_10_fc, yvar = 'n_d_Stomach_male_3', sex_b = 'male', adjust = TRUE, ncores = 16)
smerc_lung_3df = run_smerc_cancertype(data = covar_origin_10_fc, yvar = 'n_d_Lung_female_3', sex_b = 'female', adjust = TRUE, ncores = 16)
smerc_stom_3df = run_smerc_cancertype(data = covar_origin_10_fc, yvar = 'n_d_Stomach_female_3', sex_b = 'female', adjust = TRUE, ncores = 16)


smerc_lung_3dtu = run_smerc_cancertype(data = covar_origin_10_fc, pop = 'n_p_total_3', yvar = 'n_d_Lung_total_3', sex_b = 'total', adjust = FALSE, ncores = 16)
smerc_stom_3dtu = run_smerc_cancertype(data = covar_origin_10_fc, pop = 'n_p_total_3', yvar = 'n_d_Stomach_total_3', sex_b = 'total', adjust = FALSE, ncores = 16)
smerc_lung_3dmu = run_smerc_cancertype(data = covar_origin_10_fc, pop = 'n_p_male_3', yvar = 'n_d_Lung_male_3', sex_b = 'male', adjust = FALSE, ncores = 16)
smerc_stom_3dmu = run_smerc_cancertype(data = covar_origin_10_fc, pop = 'n_p_male_3', yvar = 'n_d_Stomach_male_3', sex_b = 'male', adjust = FALSE, ncores = 16)
smerc_lung_3dfu = run_smerc_cancertype(data = covar_origin_10_fc, pop = 'n_p_female_3', yvar = 'n_d_Lung_female_3', sex_b = 'female', adjust = FALSE, ncores = 16)
smerc_stom_3dfu = run_smerc_cancertype(data = covar_origin_10_fc, pop = 'n_p_female_3', yvar = 'n_d_Stomach_female_3', sex_b = 'female', adjust = FALSE, ncores = 16)

save(list = ls()[grep('^(covar_origin_10_|smerc_)', ls())],
     file = 'Scan_SMERC_2009_2013_Results.RData')

```

```{r}
#load('Scan_SMERC_2009_2013_Results.RData')
#load('Scan_DCLUST_2009_2013_Results.RData')
load(str_c(drive, '/Manuscript/Clustering_Base_sf_012222.RData'))
load(str_c(drive, '/Manuscript/Scan_SMERC_periods_1_3_vsets_1_2_allsex_Results_p005.RData'))

```

# Overview
- Incidence and mortality rates: (Sum of cases) / (Sum of the population)
- 2009-2013: all covariates included


# Lung Cancer (All sexes, periods 1-3)
## Variable set 1: education attainment higher than bachelor's degree, 65+ years old (%)
```{r Lung cancer cluster plots, fig.width=7.5}
tmap::tmap_arrange(
    tmap_smerc(covar_origin_00_fc, smerc_lung_1itu, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer incidence\n(1999-2003, All sexes, Uncontrolled)', frame = FALSE),
    tmap_smerc(covar_origin_00_fc, smerc_lung_1it_v1, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer incidence\n(1999-2003, All sexes, Variable set 1)  ', frame = FALSE),
    tmap_smerc(covar_origin_00_fc, smerc_lung_1it_v2, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer incidence\n(1999-2003, All sexes, Variable set 2)  ', frame = FALSE),
    ncol = 3
)
tmap::tmap_arrange(
    tmap_smerc(covar_origin_05_fc, smerc_lung_2itu, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer incidence\n(2004-2008, All sexes, Uncontrolled)', frame = FALSE),
    tmap_smerc(covar_origin_05_fc, smerc_lung_2it_v1, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer incidence\n(2004-2008, All sexes, Variable set 1)  ', frame = FALSE),
    tmap_smerc(covar_origin_05_fc, smerc_lung_2it_v2, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer incidence\n(2004-2008, All sexes, Variable set 2)  ', frame = FALSE),
    ncol = 3
)
tmap::tmap_arrange(
    tmap_smerc(covar_origin_10_fc, smerc_lung_3itu, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer incidence\n(2009-2013, All sexes, Uncontrolled)', frame = FALSE),
    tmap_smerc(covar_origin_10_fc, smerc_lung_3it_v1, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer incidence\n(2009-2013, All sexes, Variable set 1)  ', frame = FALSE),
    tmap_smerc(covar_origin_10_fc, smerc_lung_3it_v2, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer incidence\n(2009-2013, All sexes, Variable set 2)  ', frame = FALSE),
    ncol = 3
)

tmap::tmap_arrange(
    tmap_smerc(covar_origin_00_fc, smerc_lung_1dtu, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(1999-2003, All sexes, Uncontrolled)  ', frame = FALSE),
    tmap_smerc(covar_origin_00_fc, smerc_lung_1dt_v1, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(1999-2003, All sexes, Variable set 1)', frame = FALSE),
    tmap_smerc(covar_origin_00_fc, smerc_lung_1dt_v2, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(1999-2003, All sexes, Variable set 2)', frame = FALSE),
    ncol = 3
)
tmap::tmap_arrange(
    tmap_smerc(covar_origin_05_fc, smerc_lung_2dtu, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(2004-2008, All sexes, Uncontrolled)  ', frame = FALSE),
    tmap_smerc(covar_origin_05_fc, smerc_lung_2dt_v1, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(2004-2008, All sexes, Variable set 1)', frame = FALSE),
    tmap_smerc(covar_origin_05_fc, smerc_lung_2dt_v2, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(2004-2008, All sexes, Variable set 2)', frame = FALSE),
    ncol = 3
)
tmap::tmap_arrange(
    tmap_smerc(covar_origin_10_fc, smerc_lung_3dtu, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(2009-2013, All sexes, Uncontrolled)  ', frame = FALSE),
    tmap_smerc(covar_origin_10_fc, smerc_lung_3dt_v1, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(2009-2013, All sexes, Variable set 1)', frame = FALSE),
    tmap_smerc(covar_origin_10_fc, smerc_lung_3dt_v2, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(2009-2013, All sexes, Variable set 2)', frame = FALSE),
    ncol = 3
)

## One-shot
tmap::tmap_arrange(
    tmap_smerc(covar_origin_00_fc, smerc_lung_1dtu, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(1999-2003, All sexes, Uncontrolled)  ', frame = FALSE),
    tmap_smerc(covar_origin_00_fc, smerc_lung_1dt_v1, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(1999-2003, All sexes, Variable set 1)', frame = FALSE),
    tmap_smerc(covar_origin_00_fc, smerc_lung_1dt_v2, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(1999-2003, All sexes, Variable set 2)', frame = FALSE),
    tmap_smerc(covar_origin_05_fc, smerc_lung_2dtu, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(2004-2008, All sexes, Uncontrolled)  ', frame = FALSE),
    tmap_smerc(covar_origin_05_fc, smerc_lung_2dt_v1, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(2004-2008, All sexes, Variable set 1)', frame = FALSE),
    tmap_smerc(covar_origin_05_fc, smerc_lung_2dt_v2, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(2004-2008, All sexes, Variable set 2)', frame = FALSE),
    tmap_smerc(covar_origin_10_fc, smerc_lung_3dtu, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(2009-2013, All sexes, Uncontrolled)  ', frame = FALSE),
    tmap_smerc(covar_origin_10_fc, smerc_lung_3dt_v1, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(2009-2013, All sexes, Variable set 1)', frame = FALSE),
    tmap_smerc(covar_origin_10_fc, smerc_lung_3dt_v2, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(2009-2013, All sexes, Variable set 2)', frame = FALSE),
    ncol = 3
)


```

```{r Lung: sex stratified, eval=FALSE, include = FALSE}



tmap::tmap_arrange(
    tmap_smerc(covar_origin_10_fc, smerc_lung_3ifu, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer incidence\n(2009-2013, Female, Uncontrolled)', frame = FALSE),
    tmap_smerc(covar_origin_10_fc, smerc_lung_3if, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer incidence\n(2009-2013, Female, Controlled)  ', frame = FALSE),
    ncol = 2
)

tmap::tmap_arrange(
    tmap_smerc(covar_origin_10_fc, smerc_lung_3dfu, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(2009-2013, Female, Uncontrolled)', frame = FALSE),
    tmap_smerc(covar_origin_10_fc, smerc_lung_3df, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(2009-2013, Female, Controlled)  ', frame = FALSE),
    ncol = 2
)

tmap::tmap_arrange(
    tmap_smerc(covar_origin_10_fc, smerc_lung_3imu, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer incidence\n(2009-2013, Male, Uncontrolled)', frame = FALSE),
    tmap_smerc(covar_origin_10_fc, smerc_lung_3im, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer incidence\n(2009-2013, Male, Controlled)  ', frame = FALSE),
    ncol = 2
)
tmap::tmap_arrange(
    tmap_smerc(covar_origin_10_fc, smerc_lung_3dmu, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(2009-2013, Male, Uncontrolled)', frame = FALSE),
    tmap_smerc(covar_origin_10_fc, smerc_lung_3dm, return_ellipses = TRUE) + 
        tm_layout(title = 'Lung cancer mortality\n(2009-2013, Male, Controlled)  ', frame = FALSE),
    ncol = 2
)
```


# Stomach Cancer (2009-2013)

```{r Stomach cancer cluster plots}
tmap::tmap_arrange(
    tmap_smerc(covar_origin_00_fc, smerc_stom_1itu, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer incidence\n(1999-2003, All sexes, Uncontrolled)  ', frame = FALSE),
    tmap_smerc(covar_origin_00_fc, smerc_stom_1it_v1, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer incidence\n(1999-2003, All sexes, Variable set 1)', frame = FALSE),
    tmap_smerc(covar_origin_00_fc, smerc_stom_1it_v2, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer incidence\n(1999-2003, All sexes, Variable set 2)', frame = FALSE),
    ncol = 3
)
tmap::tmap_arrange(
    tmap_smerc(covar_origin_05_fc, smerc_stom_2itu, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer incidence\n(2004-2008, All sexes, Uncontrolled)  ', frame = FALSE),
    tmap_smerc(covar_origin_05_fc, smerc_stom_2it_v1, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer incidence\n(2004-2008, All sexes, Variable set 1)', frame = FALSE),
    tmap_smerc(covar_origin_05_fc, smerc_stom_2it_v2, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer incidence\n(2004-208, All sexes, Variable set 2)', frame = FALSE),
    ncol = 3
)
tmap::tmap_arrange(
    tmap_smerc(covar_origin_10_fc, smerc_stom_3itu, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer incidence\n(2009-2013, All sexes, Uncontrolled)  ', frame = FALSE),
    tmap_smerc(covar_origin_10_fc, smerc_stom_3it_v1, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer incidence\n(2009-2013, All sexes, Variable set 1)', frame = FALSE),
    tmap_smerc(covar_origin_10_fc, smerc_stom_3it_v2, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer incidence\n(2009-2013, All sexes, Variable set 2)', frame = FALSE),
    ncol = 3
)


tmap::tmap_arrange(
    tmap_smerc(covar_origin_00_fc, smerc_stom_1dtu, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer mortality\n(1999-2003, All sexes, Uncontrolled)  ', frame = FALSE),
    tmap_smerc(covar_origin_00_fc, smerc_stom_1dt_v1, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer mortality\n(1999-2003, All sexes, Variable set 1)', frame = FALSE),
    tmap_smerc(covar_origin_00_fc, smerc_stom_1dt_v2, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer mortality\n(1999-2003, All sexes, Variable set 2)', frame = FALSE),
    ncol = 3
)

tmap::tmap_arrange(
    tmap_smerc(covar_origin_05_fc, smerc_stom_2dtu, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer mortality\n(2004-2008, All sexes, Uncontrolled)  ', frame = FALSE),
    tmap_smerc(covar_origin_05_fc, smerc_stom_2dt_v1, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer mortality\n(2004-2008, All sexes, Variable set 1)', frame = FALSE),
    tmap_smerc(covar_origin_05_fc, smerc_stom_2dt_v2, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer mortality\n(2004-2008, All sexes, Variable set 2)', frame = FALSE),
    ncol = 3
)

tmap::tmap_arrange(
    tmap_smerc(covar_origin_10_fc, smerc_stom_3dtu, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer mortality\n(2009-2013, All sexes, Uncontrolled)  ', frame = FALSE),
    tmap_smerc(covar_origin_10_fc, smerc_stom_3dt_v1, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer mortality\n(2009-2013, All sexes, Variable set 1)', frame = FALSE),
    tmap_smerc(covar_origin_10_fc, smerc_stom_3dt_v2, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer mortality\n(2009-2013, All sexes, Variable set 2)', frame = FALSE),
    ncol = 3
)

```


```{r eval=FALSE}
tmap::tmap_arrange(
    tmap_smerc(covar_origin_10_fc, smerc_stom_3dtu, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer mortality\n(2009-2013, All sexes, Uncontrolled)', frame = FALSE, main.title.size = 10),
    tmap_smerc(covar_origin_10_fc, smerc_stom_3dt, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer mortality\n(2009-2013, All sexes, Controlled)  ', frame = FALSE, main.title.size = 10),
    ncol = 2
)

tmap::tmap_arrange(
    tmap_smerc(covar_origin_10_fc, smerc_stom_3ifu, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer incidence\n(2009-2013, Female, Uncontrolled)', frame = FALSE),
    tmap_smerc(covar_origin_10_fc, smerc_stom_3if, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer incidence\n(2009-2013, Female, Controlled)  ', frame = FALSE),
    ncol = 2
)

tmap::tmap_arrange(
    tmap_smerc(covar_origin_10_fc, smerc_stom_3dfu, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer mortality\n(2009-2013, Female, Uncontrolled)', frame = FALSE),
    tmap_smerc(covar_origin_10_fc, smerc_stom_3df, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer mortality\n(2009-2013, Female, Controlled)  ', frame = FALSE),
    ncol = 2
)

tmap::tmap_arrange(
    tmap_smerc(covar_origin_10_fc, smerc_stom_3imu, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer incidence\n(2009-2013, Male, Uncontrolled)', frame = FALSE),
    tmap_smerc(covar_origin_10_fc, smerc_stom_3im, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer incidence\n(2009-2013, Male, Controlled)  ', frame = FALSE),
    ncol = 2
)

tmap::tmap_arrange(
    tmap_smerc(covar_origin_10_fc, smerc_stom_3dmu, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer mortality\n(2009-2013, Male, Uncontrolled)', frame = FALSE),
    tmap_smerc(covar_origin_10_fc, smerc_stom_3dm, return_ellipses = TRUE) + 
        tm_layout(title = 'Stomach cancer mortality\n(2009-2013, Male, Controlled)  ', frame = FALSE),
    ncol = 2
)

```


# Tables for regression analysis (Lung cancer)
```{r Tables for regression analysis, results = "asis"}
reg_lung_3it = regress_counts(data = covar_origin_10_fc, yvar = 'n_i_Lung_total_3', sex_b = 'total')
reg_stom_3it = regress_counts(data = covar_origin_10_fc, yvar = 'n_i_Stomach_total_3', sex_b = 'total', add_var = 'p_candiag_sto')
reg_lung_3im = regress_counts(data = covar_origin_10_fc, yvar = 'n_i_Lung_male_3', sex_b = 'male')
reg_stom_3im = regress_counts(data = covar_origin_10_fc, yvar = 'n_i_Stomach_male_3', sex_b = 'male', add_var = 'p_candiag_sto')
reg_lung_3if = regress_counts(data = covar_origin_10_fc, yvar = 'n_i_Lung_female_3', sex_b = 'female')
reg_stom_3if = regress_counts(data = covar_origin_10_fc, yvar = 'n_i_Stomach_female_3', sex_b = 'female', add_var = 'p_candiag_sto')

# Mortality (d)
reg_lung_3dt = regress_counts(data = covar_origin_10_fc, yvar = 'n_d_Lung_total_3', sex_b = 'total')
reg_stom_3dt = regress_counts(data = covar_origin_10_fc, yvar = 'n_d_Stomach_total_3', sex_b = 'total', add_var = 'p_candiag_sto')
reg_lung_3dm = regress_counts(data = covar_origin_10_fc, yvar = 'n_d_Lung_male_3', sex_b = 'male')
reg_stom_3dm = regress_counts(data = covar_origin_10_fc, yvar = 'n_d_Stomach_male_3', sex_b = 'male', add_var = 'p_candiag_sto')
reg_lung_3df = regress_counts(data = covar_origin_10_fc, yvar = 'n_d_Lung_female_3', sex_b = 'female')
reg_stom_3df = regress_counts(data = covar_origin_10_fc, yvar = 'n_d_Stomach_female_3', sex_b = 'female', add_var = 'p_candiag_sto')


description = data.frame(
    Variable = names(reg_stom_3dt$coefficients)[-1],
    Description = c("Higher than bachelor's degree (%)",
                    "Stomach cancer diagnosis rate (%; only included in stomach cancer models)",
                    "Unemployment rate (%)",
                    "Change rate of land price (%)",
                    "Walking regularly (%)",
                    "Obesity rate (%)",
                    "Alcohol consumption rate (%; more frequent than once a month)",
                    "Physical activity rate (%)",
                    "Smoking (%)",
                    "Average PM10 exposure",
                    "Average NO2 exposure",
                    "Average NDVI (unitless)",
                    "Total CO emission",
                    "Total NOx emission",
                    "Total SOx emission",
                    "Total TSP emission",
                    "Total PM10 emission",
                    "Total VOC emission",
                    "Total NH3 emission")
)

kable(description, format = "html")

macro_stargazer = function(reg_results,
                           title1 = "cancer") {
    
    stargazer(reg_results[[1]], reg_results[[2]],
              type = "html",
              title = sprintf("Poisson regression models of %s for incidence and mortality", title1),
              column.labels = c("Incidence", "Mortality"),
              colnames = FALSE,
              header = FALSE,
              model.numbers = FALSE,
              keep.stat = c("aic", "f"),
              notes.align = 'l')
    }

macro_stargazer(list(reg_lung_3it, reg_lung_3dt), "lung cancer (all sexes)")
macro_stargazer(list(reg_lung_3if, reg_lung_3df), "lung cancer (female)")
macro_stargazer(list(reg_lung_3im, reg_lung_3dm), "lung cancer (male)")

```

# Tables for regression analysis (Stomach cancer)
```{r Tables: stomach cancer, results = 'asis'}
macro_stargazer(list(reg_stom_3it, reg_stom_3dt), "stomach cancer (all sexes)")
macro_stargazer(list(reg_stom_3if, reg_stom_3df), "stomach cancer (female)")
macro_stargazer(list(reg_stom_3im, reg_stom_3dm), "stomach cancer (male)")


```