---
title: "Covariate clearing"
author: "Insang Song"
date: 12-11-2021
theme: "spacelab"
output:
  html_document:
    toc: true
    fig_caption: true
---

```{r}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```


# Base settings

```{r}
if (!require(pacman)) { install.packages('pacman') } 
options(repos = 'https://cran.seoul.go.kr')
p_load(tidyverse, sf, stars, raster, starsExtra, readxl, here, spdep, missRanger, GGally, smerc, DClusterm)
username = 'isong'
basedir = sprintf('/mnt/c/Users/%s/Documents/', username)
rdatafiles = list.files(path = str_c(basedir, 'GP/'), pattern = '*.RData', full.names = TRUE)

dbdir = here::here()

```


# 2001 (TODO)
```{r, include = FALSE, eval = FALSE}
load(rdatafiles[1])
ls()


st_crs(carreg) = 5179
plot(carreg)
sgg = st_transform(carreg, 5174)

#plot(kngii)
ndvi_stars = st_as_stars(ndvi_mean)
st_crs(ndvi_stars) = 5174
#sgg_ndvi_test = starsExtra::extract2(ndvi_stars, sgg, function(x) mean(x, na.rm = T))
#carreg$ndvi_mean = sgg_ndvi_test
plot(carreg[,'ndvi_mean'])

plot(kngii_stars)
plot(sgg %>% st_geometry, add = T, border = 'red')
```


# 2015
```{r, results = 'hide'}
#load(rdatafiles[4])
load(str_c(dbdir, '/Base_Data_2015.RData'))
ls()

targ_year = 2015

# Cancer mortality (number only)
cmorts = list.files(pattern = '^cancerMor',
                    path = dbdir,
                    full.names = TRUE)
cmorts = lapply(cmorts, function(x) read.csv(x, fileEncoding = 'CP949'))
cmorts = lapply(cmorts,
                function(x) {
                colnames(x) = c('cause0', 'cause', 'sgg_cd', 'sgg_nm', 'sex0', 'sex', 'type0', 'type', 'unit', paste('Y', 1998:2019, sep=''), 'x')
                x = x %>%
                  mutate(cancer_type_e = plyr::mapvalues(cause, unique(cause), c('Stomach', 'Colorectal', 'Liver', 'Lung', 'Breast', 'Cervical', 'Prostate'))) 
                return(x)
                }
)
cmorts_df = do.call(rbind, cmorts) %>%
    dplyr::select(sgg_cd, cancer_type_e, sex0, type0, sym(str_c('Y', 2015))) %>%
    filter(type0 == 'T1') %>%
    mutate(sex = plyr::mapvalues(sex0, 0:2, c('total', 'male', 'female'))) %>%
    dplyr::select(-sex0, -type0) %>%
    pivot_wider(names_from = c(cancer_type_e, sex), values_from = Y2015)

# Total Population by sex
midpop = read.csv(str_c(dbdir, '/MidPopulation_2000_2020.csv'), fileEncoding = 'CP949')
midpop = midpop %>%
    dplyr::select(1, 3, 6, 10:14)
colnames(midpop) = c('sggcd', 'sex0', 'agegroup', 'Y2000', 'Y2005', 'Y2010', 'Y2015', 'Y2020')
midpop = midpop %>%
    dplyr::select(1:3, ends_with(targ_year)) %>%
    filter(agegroup == '계') %>%
    pivot_wider(names_from = sex0, values_from = Y2015) %>%
    dplyr::select(-2) %>%
    rename(pop_total = `0`,
           pop_male = `1`,
           pop_female = `2`)


# NDVI
st_crs(carreg) = 5179
#plot(carreg)
sgg = carreg#st_transform(carreg, 5174)
ndvi_stars = st_as_stars(ndvi_mean)
st_crs(ndvi_stars) = 5179
sgg_ndvi = starsExtra::extract2(ndvi_stars, sgg, function(x) mean(x, na.rm = T))

# Air pollution exposure
airpol = read.csv(str_c(dbdir, '/Covariates/Airpollution/2015_new.csv'), fileEncoding = 'CP949')
airpol = airpol %>%
    transmute(sggcd = SGG_cd,
              ap_PM10_pred = PM10_pred,
              ap_NO2_pred = NO2_pred,
              ap_PM25_pred = PM25_pred)

# Emission
emission = st_as_stars(em.2015, crs = 5174)
st_crs(emission) = 5174
sgg_5174 = st_transform(sgg, 5174)
sgg_emission = starsExtra::extract2(emission, sgg_5174, function(x) sum(x, na.rm = T))
sgg_emission = sgg_emission %>%
    as.data.frame
colnames(sgg_emission) = str_c('sum_', attr(emission, 'dimensions')$band$values)

# Education attainment
educ = read.csv(str_c(dbdir, '/Covariates/Education_2015.csv'), fileEncoding = 'CP949') %>%
    .[,c(1, 4:7)]
colnames(educ) = c('sggcd', 'total_6yo', 'bachelor', 'masters', 'doctorate')
educ = educ %>%
    transmute(sggcd = as.integer(str_split(sggcd, ' ', simplify = TRUE)[,1]),
              p_eduhigh = 100 * (bachelor + masters + doctorate) / total_6yo)


# KCDC Community Health Data: separate tables: 2010, 2015
## KCDC code to others
code_conv = read_xlsx(str_c(dbdir, '/행정자치부_심평원_통계청_코드_연계표_211119.xlsx'), sheet = 4)
code_conv = code_conv %>% 
  dplyr::select(SIGUNGU_PSEUDO, ends_with('2015')) %>%
  rename(SGIS = SGIS_2015,
         SIGUNGU_KCDC = SIGUNGU_PSEUDO) %>%
  mutate(SGIS = str_sub(SGIS, 1, 5)) %>%
  filter(!is.na(SGIS))

## Main
kcdc_csvs = 
list.files(pattern = '시군구별_*.*.csv$', 
           path = str_c(dbdir, "/Covariates/"),
           full.names = TRUE)
kcdc_list = lapply(kcdc_csvs, 
    function(x) read_csv(x, skip = 1, locale = locale(encoding = 'CP949')) %>%
          mutate_at(.vars = vars(-1:-3), .funs = list(~as.numeric(.))))

kcdc_cns = 
  c('sido', 'sigungu', 'sub_sigungu',
             str_c(rep(c('N_', 'CR_', 'CR_SE_', 'SR_', 'SR_SE_'), 13), rep(2008:2020, each = 5)))
kcdc_cn4 = c('sido', 'sigungu', 'sub_sigungu',
             str_c(rep(c('N_', 'CR_', 'CR_SE_', 'SR_', 'SR_SE_'), 12), rep(2009:2020, each = 5)))
colnames(kcdc_list[[1]]) = kcdc_cns
colnames(kcdc_list[[2]]) = kcdc_cns[-59:-63]
colnames(kcdc_list[[3]]) = kcdc_cns
colnames(kcdc_list[[4]]) = kcdc_cn4[-grep('2018$', kcdc_cn4)]
colnames(kcdc_list[[5]]) = kcdc_cns


kcdc_covars = kcdc_list %>%
  lapply(function(x) x %>% 
      mutate_at(.vars = vars(1:3), .funs = list(~gsub('[[:blank:]]|[가-힣]', '', .))) %>%
      transmute(SIGUNGU_KCDC = ifelse(sub_sigungu == '', sigungu, sub_sigungu),
                SR = !!sym('SR_2015'))) %>%
      mapply(function(x, y) {colnames(x)[2] = y; return(x)},
              ., c('r_walking', 'r_obesity', 'r_alcoholmonth', 'r_physmid', 'r_smoking') %>% split(., 1:5), SIMPLIFY = FALSE) %>%
      plyr::join_all(.)
kcdc_covars = kcdc_covars %>%
  left_join(code_conv, .) %>%
  mutate(SGIS = as.integer(SGIS))

'''
colnames(kcdc_list[[1]]) = str_c('Walking_', kcdc_cns)
colnames(kcdc_list[[2]]) = str_c('Obesity_', kcdc_cns[-59:-63])
colnames(kcdc_list[[3]]) = str_c('AlcoholM_', kcdc_cns)
colnames(kcdc_list[[4]]) = str_c('PhysMid_', kcdc_cn4[-grep('2018$', kcdc_cn4)])
colnames(kcdc_list[[5]]) = str_c('Smoking_', kcdc_cns)
'''




# KCDC Community Health Data
kcdc = readxl::read_xlsx(str_c(dbdir, '/Covariates/CommunityHealth_Covariates_KCDC.xlsx'), sheet = 'Data_2015')
kcdc_sub = kcdc %>% 
    dplyr::select(2:5, #contains('비만율'), contains('음주율'), contains('신체활동'), contains(' 흡연율'), contains('현재흡연율'), 
    contains('암검진'), #contains('걷기'),
    contains('건강검진수검율'), contains('암검진율'), contains('실업률'), contains('지가변동률'), contains('산림면적비율'),
    contains('암검진_대상인원'), contains('암검진_수검인원')) %>%
    transmute(sggcd = 코드,
         sido = 시도,
         sigungu = 시군구,
         sdsgg = 지역,
         #p_obese_std = 비만율_자가보고_표준화율,
         #p_obese_cru = 비만율_자가보고_조율,
         #p_alcl_std = 평생음주율_표준화율,
         #p_alcl_cru = 평생음주율_조율,
         #p_alcy_std = 연간음주율_표준화율,
         #p_alcy_cru = 연간음주율_조율,
         #p_smk_std = 현재흡연율_표준화율,
         #p_smk_cru = 현재흡연율_조율,
         #p_active_std = `중등도신체활동실천율_표준화율`,
         #p_active_cru = `중등도신체활동실천율_조율`,
         #p_walking_std = `걷기실천율_표준화율`,
         #p_walking_cru = `걷기실천율_조율`,
         p_candiag_std = 암검진율_표준화율,
         p_candiag_cru = 암검진율_조율,
         p_candiag_sto = 위암검진_수검인원/위암검진_대상인원 * 100,
         p_candiag_col = 대장암검진_수검인원/대장암검진_대상인원 * 100,
         p_candiag_liv = 간암검진_수검인원/간암검진_대상인원 * 100,
         p_candiag_bre = 유방암검진_수검인원/유방암검진_대상인원 * 100,
         p_candiag_cer = 자궁경부암검진_수검인원/자궁경부암검진_대상인원 * 100,
         r_unemp = 실업률,
         r_landprice = 지가변동률,
         r_forest = 산림면적비율) %>% # 산림면적비율 = 산림면적/도시면적 * 100 (may exceed 100)
    # for data-specific problem: different data granularity of availability
    mutate(sggcd_pseudo = ifelse(grepl('^29$', sggcd), 29010, ifelse(nchar(sggcd) == 5, str_sub(sggcd, 1, 4), sggcd)),
           sggcd_unemp = ifelse(grepl('^[1-2][0-9]|^39', sggcd), str_sub(sggcd, 1, 2), ifelse(grepl('[3][0-8]..[0-9]', sggcd), str_sub(sggcd, 1, 4), sggcd))) %>%
    mutate(sigungu_b = if_else(grepl('[[:blank:]]', sigungu), 
                              str_split(sigungu, ' ', simplify = TRUE)[,1], 
                              str_c(sido, sigungu))
          )
kcdc_sub_fctrs = sapply(kcdc_sub, function(x) !is.character(x) & !is.factor(x)) %>%
  as.logical %>%
  which %>%
  .[-1]
kcdc_sub = kcdc_sub %>%
    group_by(sggcd_pseudo) %>%
    mutate_at(vars(-group_cols(), -sggcd, c(kcdc_sub_fctrs), -r_unemp), list(~ifelse(any(!is.na(.)), .[which(!is.na(.))], .))) %>%
    ungroup %>%
    group_by(sggcd_unemp) %>%
    mutate_at(vars(-group_cols(), -sggcd, c(kcdc_sub_fctrs)), list(~ifelse(any(!is.na(.)), .[which(!is.na(.))], .))) %>%
    #ungroup %>%
    #group_by(sggcd) %>%
    # take the first row (sigungu-representative) from each sigungu code
    #summarize_at(vars(-group_cols()), list(~.[which(!is.na(.))])) %>%
    ungroup %>%
    mutate(sggcd = ifelse(sggcd == 29, 29010, sggcd))

sgg2015 = sgg %>%
  mutate(NDVI_mean = sgg_ndvi) %>%
  bind_cols(sgg_emission) %>%
  left_join(cmorts_df, by = c('SGGCD' = 'sgg_cd')) %>%
  left_join(midpop, by = c('SGGCD' = 'sggcd')) %>%
  left_join(kcdc_sub %>% filter(!duplicated(sggcd)), by = c('SGGCD' = 'sggcd')) %>%
  left_join(kcdc_covars, by = c('SGGCD' = 'SGIS')) %>%
  left_join(airpol, by = c('SGGCD' = 'sggcd')) %>%
  left_join(educ, by = c('SGGCD' = 'sggcd')) 

## Imputation with missForest
#sgg2015_d = sgg2015 %>%
#  st_drop_geometry()
#sgg2015_di = missRanger::missRanger(sgg2015_d)
#sgg2015_dif = bind_cols(sgg2015_di, geom = sgg2015$geom) %>%
#    st_as_sf(., sf_column_name = 'geom')
#GGally::ggpairs(sgg2015_dif %>% st_drop_geometry %>% dplyr::select_if(is.numeric) %>%
#                dplyr::select(ends_with('_std'), starts_with('r_'), starts_with('ap_'), starts_with('sum_'), 'NDVI_mean'))


```
```{r}
DT::datatable(sgg2015_dif %>% st_drop_geometry)
```

# 2015 Clustering

## Colorectal (all sexes) example without covariates
```{r}
eltest_colrec = smerc::elliptic.test(st_coordinates(st_centroid(sgg2015_dif)), cases = sgg2015_dif$Colorectal_total, pop = sgg2015_dif$pop_total)
eltest_colrec
plot(eltest_colrec)

sgg2015_df = sgg2015 %>%
  bind_cols(st_coordinates(st_centroid(.)) %>% as_tibble) %>%
  st_drop_geometry

form_pois_colrec = as.formula(str_c('Colorectal_total~', str_c(colnames(sgg2015)[c(3:10, 42, 46:47, 53:59, 61)], collapse = '+')))
#form_pois_colrec = update(form_pois_colrec, ~.+offset(log(pop_total)))
reg_pois_colrec = glm(formula = form_pois_colrec, data= sgg2015, family = poisson(link = 'log'))

eltest_colrec = smerc::elliptic.test(st_coordinates(st_centroid(sgg2015)), cases = reg_pois_colrec$residuals, pop = reg_pois_colrec$data$pop_total)
sgg2015$E_Colrec = (sum(sgg2015$Colorectal_total) / sum(sgg2015$pop_total)) * sgg2015$pop_total
form_pois_colrec = Colorectal_total ~offset(log(E_Colrec)) + 1
reg_pois_colrec_no = glm(formula = form_pois_colrec, data= sgg2015, family = poisson(link = 'log'))

eltest_colrec = smerc::elliptic.test(st_coordinates(st_centroid(sgg2015)), cases = sgg2015$Colorectal_total, pop = reg_pois_colrec$fitted.values)
eltest_colrec
plot(eltest_colrec)

options(mc.cores = 20)
rownames(sgg2015) = sgg2015$SGGCD
eltest_colrec <- DetectClustersModel(sgg2015 %>% as('Spatial'), radius = 1000000,
    thegrid = sgg2015_df %>% dplyr::select(X, Y), fractpop = 0.5,
    alpha = 0.05, typeCluster = "S", R = NULL, model0 = reg_pois_colrec,
    ClusterSizeContribution = "pop_total")

eltest_colrec_noa <- DetectClustersModel(sgg2015 %>% as('Spatial'),
    thegrid = sgg2015_df %>% dplyr::select(X, Y), fractpop = 0.5,
    alpha = 0.05, typeCluster = "S", R = NULL, model0 = reg_pois_colrec_no,
    ClusterSizeContribution = "pop_total")

sgg2015$CLUSTERS = get.allknclusters(sgg2015_df %>% rename(x = X, y = Y), eltest_colrec)
sgg2015$CLUSTERS = get.allknclusters(sgg2015, slimknclusters(sgg2015 %>% as('Spatial'), eltest_colrec, 10))
get.knclusters(sgg2015_df %>% rename(x = X, y = Y), eltest_colrec_noa)
```


```{r}
## Satscan software comparison
## Basic: location / case / population (expected number if covariate adjustment is applied)
sgg2015 = sgg2015 %>%
  mutate(E_colorec = reg_pois_colrec$fitted.values)
mapsf::mf_choro(sgg2015, var = 27)

reg_pois_colrec = glm(formula = form_pois_colrec, data= sgg2015, family = poisson(link = 'log'))
sgg2015_df = sgg2015 %>%
  bind_cols(st_coordinates(st_centroid(.)) %>% as_tibble) %>%
  st_drop_geometry %>%
  mutate(E_colorec = reg_pois_colrec$fitted.values,
         E_colorec_res = reg_pois_colrec$residuals)

sgg2015_df %>%
  dplyr::select(SGGCD, Colorectal_total) %>%
  write.csv(., '/mnt/d/Colorectal.cas', row.names = FALSE)
sgg2015_df %>%
  dplyr::select(SGGCD, E_colorec_res) %>%
  write.csv(., '/mnt/d/Colorectal_residuals.cas', row.names = FALSE)
sgg2015_df %>%
  dplyr::select(SGGCD, X, Y) %>%
  write.csv(., '/mnt/d/Colorectal.geo', row.names = FALSE)
sgg2015_df %>%
  mutate(time = 2015) %>%
  dplyr::select(SGGCD, time, E_colorec) %>%
  write.csv(., '/mnt/d/Colorectal.pop', row.names = FALSE)
sgg2015_df %>%
  mutate(time = 2015) %>%
  dplyr::select(SGGCD, time, E_colorec, pop_total) %>%
  write.csv(., '/mnt/d/Colorectal.pop', row.names = FALSE)
```


```{r}
run_smerc_cancertype = function(data = sgg2015, yvar = "Lung_total", ncores = 8) {
  form_pois = as.formula(str_c(yvar, '~', str_c(colnames(sgg2015)[c(3:10, 42, 46:47, 53:59, 61)], collapse = '+')))
  reg_pois = glm(formula = form_pois, data= data, family = poisson(link = 'log'))
  cls = parallel::makeCluster(ncores)
  data_df = st_drop_geometry(data)
  eltest = smerc::elliptic.test(st_coordinates(st_centroid(data)), 
            cases = unlist(data_df[, yvar]), 
            pop = reg_pois$fitted.values,
            shape = c(1, 1.5, 2, 2.5, 3, 4, 5, 6),
            nangle = c(1, 4, 6, 12, 12, 12, 15, 18),
            cl = cls)
  return(eltest)
}

smerc_lung_t = run_smerc_cancertype()
```


```{r}
#options(mc.cores = 12)
cls = parallel::makeCluster(12)
eltest_colrec = smerc::elliptic.test(st_coordinates(st_centroid(sgg2015)), 
          cases = sgg2015$Colorectal_total, 
          pop = reg_pois_colrec$fitted.values,
          shape = c(1, 1.5, 2, 2.5, 3, 4, 5, 6),
          nangle = c(1, 4, 6, 12, 12, 12, 15, 18),
          cl = cls)
plot(eltest_colrec)
```


```{r}
#sgg2015_s = rmapshaper::ms_simplify(sgg2015, 0.2, keep_shapes = TRUE, drop_null_geometries = TRUE)
#sgg2015_ss = sgg2015_s %>% filter(!is.na(r_unemp))
#sgg2015_w = spdep::poly2nb(sgg2015_ss)
#moran.test(sgg2015_ss$r_unemp, listw = nb2listw(sgg2015_w, zero.policy = TRUE), zero.policy = TRUE)


```